# Generated by Django 5.0.1 on 2024-03-16 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makaan', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='phone_no',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 16)),
        ),
    ]
